### ISSUE TITLE
no luck with firefox 70

### ISSUE THREAD

**Issue by shining** [pocc/no-wysiwyg#2]
The chrome extension works fine in chromium 78 but I had no luck with the firefox extension in firefox 70.
If I execute manually https://raw.githubusercontent.com/pocc/no-wysiwyg/master/src/index.js in the console, it works though.
And this version works fine as a bookmark : https://raw.githubusercontent.com/kfahy/slack-disable-wysiwyg-bookmarklet/master/index.js

**Comment by pocc** [comment]
I just tested in Firefox 70.0.1 (64-bit) on Macos 10.14 and it works as expected. Can you test on a different computer (and provide details environment info about this one)?

**Comment by shining** [comment]
Firefox 70.0.1 (64 bits) on Linux (Debian 10), downloaded here : https://www.mozilla.org/fr/firefox/new/
Anyway, if slack releases a new version soon enough that makes this configurable, don't worry !

**Comment by pocc** [comment]
Per your last comment, I'm going to close this, but please reply here if you can reproduce this.
